name: Build lectureStudio
on:
  push:
    # Run pipeline for commits on branch 'main' and on 'feature/<stuff>'
    branches:
      - main
      - 'feature/**'
      - 'testing/**'
    # Run pipeline for release tags
    #tags:
    #  - 'v*.*.*'

jobs:
  # Build lectureStudio for Linux
  lecturestudio-build-linux:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Start message
        run: echo "Started CI build (lectureStudio)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: maxkratz/lecturestudiobuilder:latest
      - name: Build lectureStudio in Docker container
        run: docker run --rm -v $PWD:/data maxkratz/lecturestudiobuilder:latest /bin/bash -c "cd /data && mvn install -DskipTests --no-transfer-progress"
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: lecturestudio-build-linux
          path: target/lectureStudio-*.zip

  # Build lectureStudio for Windows
  lecturestudio-build-windows:
    runs-on: [windows-2022]
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.7
      - name: Install dependencies
        run: |
          choco install wget curl unzip zip --no-progress
      - name: Check out repository code
        uses: actions/checkout@v2
      # ---
      # Temporary hack to resolve missing webrtc-java dependency
      - name: Create folder
        run: |
          New-Item -ItemType Directory -Force -Path .\m2\repository\dev\onvoid\webrtc
      - name: Inject missing webrtc-java dependency
        run: |
          cp -r ./lib/mvn/* .\m2\repository\dev\onvoid\webrtc\
      # ---
      - name: Build lectureStudio
        run: bash -c 'mvn install -DskipTests --no-transfer-progress -P !package:msi -Dmaven.repo.local="${PWD}/m2/repository"'
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: lecturestudio-build-windows
          path: lect-packager/lect-jpackage/*
