name: Build lectureStudio
on:
  push:
    # Run pipeline for commits on branch 'main' and on 'feature/<stuff>'
    branches:
      - main
      - 'feature/**'
    # Run pipeline for release tags
    #tags:
    #  - 'v*.*.*'

jobs:
  # Build Eclipse eMoflon Linux user
  build-lecturestudio-linux:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Start message
        run: echo "Started CI build (lectureStudio)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: maxkratz/lecturestudiobuilder:latest
