name: Build lectureStudio
on:
  push:
    # Run pipeline for commits on branch 'main' and on 'feature/<stuff>'
    branches:
      - main
      - 'feature/**'
    # Run pipeline for release tags
    #tags:
    #  - 'v*.*.*'

jobs:
  # Build lectureStudio for Linux
  lecturestudio-build-linux:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Start message
        run: echo "Started CI build (lectureStudio)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Git test
        run: git shortlog -s -n  | awk '{ sum += $1; } END { print sum; }' "$@"
