name: Build lectureStudio
on:
  push:
    # Run pipeline for commits on branch 'main' and on 'feature/<stuff>'
    branches:
      - main
      - 'feature/**'
    # Run pipeline for release tags
    #tags:
    #  - 'v*.*.*'

jobs:
  # Build lectureStudio for Linux
  build-lecturestudio-linux:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Start message
        run: echo "Started CI build (lectureStudio)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: maxkratz/lecturestudiobuilder:latest
      - name: Build lectureStudio in Docker container
        run: docker run --rm -v $PWD:/data maxkratz/lecturestudiobuilder:latest /bin/bash -c "cd /data && mvn install -DskipTests --no-transfer-progress"
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: lectureStudio-build
          path: lectureStudio-*.zip
